/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddServerDialog: typeof import('./src/components/AddServerDialog.vue')['default']
    DialogClose: typeof import('radix-vue')['DialogClose']
    DialogContent: typeof import('radix-vue')['DialogContent']
    DialogDescription: typeof import('radix-vue')['DialogDescription']
    DialogOverlay: typeof import('radix-vue')['DialogOverlay']
    DialogPortal: typeof import('radix-vue')['DialogPortal']
    DialogRoot: typeof import('radix-vue')['DialogRoot']
    DialogTitle: typeof import('radix-vue')['DialogTitle']
    DialogTrigger: typeof import('radix-vue')['DialogTrigger']
    DropdownMenuContent: typeof import('radix-vue')['DropdownMenuContent']
    DropdownMenuPortal: typeof import('radix-vue')['DropdownMenuPortal']
    DropdownMenuRoot: typeof import('radix-vue')['DropdownMenuRoot']
    DropdownMenuTrigger: typeof import('radix-vue')['DropdownMenuTrigger']
    NumberFieldDecrement: typeof import('radix-vue')['NumberFieldDecrement']
    NumberFieldIncrement: typeof import('radix-vue')['NumberFieldIncrement']
    NumberFieldInput: typeof import('radix-vue')['NumberFieldInput']
    NumberFieldRoot: typeof import('radix-vue')['NumberFieldRoot']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SwitchRoot: typeof import('radix-vue')['SwitchRoot']
    SwitchThumb: typeof import('radix-vue')['SwitchThumb']
    TheAccount: typeof import('./src/components/icons/TheAccount.vue')['default']
    TheArrow: typeof import('./src/components/icons/TheArrow.vue')['default']
    TheBad: typeof import('./src/components/icons/TheBad.vue')['default']
    TheCash: typeof import('./src/components/icons/TheCash.vue')['default']
    TheClose: typeof import('./src/components/icons/TheClose.vue')['default']
    TheCross: typeof import('./src/components/icons/TheCross.vue')['default']
    TheDialog: typeof import('./src/components/ui/TheDialog.vue')['default']
    TheDollar: typeof import('./src/components/icons/TheDollar.vue')['default']
    TheFile: typeof import('./src/components/icons/TheFile.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    TheLink: typeof import('./src/components/icons/TheLink.vue')['default']
    TheLogo: typeof import('./src/components/icons/TheLogo.vue')['default']
    TheMens: typeof import('./src/components/icons/TheMens.vue')['default']
    TheMinus: typeof import('./src/components/icons/TheMinus.vue')['default']
    TheOko: typeof import('./src/components/icons/TheOko.vue')['default']
    TheOkoLine: typeof import('./src/components/icons/TheOkoLine.vue')['default']
    ThePlus: typeof import('./src/components/icons/ThePlus.vue')['default']
    TheSucsess: typeof import('./src/components/icons/TheSucsess.vue')['default']
    TheSwitcher: typeof import('./src/components/ui/TheSwitcher.vue')['default']
  }
}
