/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DropdownMenuContent: typeof import('radix-vue')['DropdownMenuContent']
    DropdownMenuPortal: typeof import('radix-vue')['DropdownMenuPortal']
    DropdownMenuRoot: typeof import('radix-vue')['DropdownMenuRoot']
    DropdownMenuTrigger: typeof import('radix-vue')['DropdownMenuTrigger']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheAccount: typeof import('./src/components/icons/TheAccount.vue')['default']
    TheArrow: typeof import('./src/components/icons/TheArrow.vue')['default']
    TheCash: typeof import('./src/components/icons/TheCash.vue')['default']
    TheDollar: typeof import('./src/components/icons/TheDollar.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    TheLogo: typeof import('./src/components/icons/TheLogo.vue')['default']
    TheMens: typeof import('./src/components/icons/TheMens.vue')['default']
  }
}
